namespace Pankha.Tray.Models;

/// <summary>
/// UI dropdown options - provides access to auto-generated values from ui-options.json
/// This provides a single source of truth for all configuration dropdown values
/// shared between the frontend web dashboard and the tray application.
/// Values are generated at build-time by build.ps1 from frontend/src/config/ui-options.json
/// </summary>
public class UIOptions
{
    private static readonly Lazy<UIOptions> _instance = new(() => new UIOptions());
    public static UIOptions Instance => _instance.Value;

    private UIOptions() { }

    /// <summary>
    /// Get update interval options (Agent Rate) in seconds
    /// </summary>
    public double[] GetUpdateIntervals() => UIOptionsAutoGenerated.UpdateIntervals;

    /// <summary>
    /// Get fan step options (percentage)
    /// </summary>
    public (int Value, string Label)[] GetFanSteps() => UIOptionsAutoGenerated.FanSteps;

    /// <summary>
    /// Get hysteresis options in °C
    /// </summary>
    public (double Value, string Label)[] GetHysteresisOptions() => UIOptionsAutoGenerated.HysteresisOptions;

    /// <summary>
    /// Get emergency temperature options in °C
    /// </summary>
    public int[] GetEmergencyTemps() => UIOptionsAutoGenerated.EmergencyTemps;

    /// <summary>
    /// Get log level options
    /// </summary>
    public (string Value, string Label)[] GetLogLevels() => UIOptionsAutoGenerated.LogLevels;

    /// <summary>
    /// Get failsafe speed options (percentage) - fan speed when backend disconnected
    /// </summary>
    public (int Value, string Label)[] GetFailsafeSpeedOptions() => UIOptionsAutoGenerated.FailsafeSpeedOptions;
}
