namespace Pankha.Tray.Models;

/// <summary>
/// UI dropdown options - provides access to auto-generated values from ui-options.json
/// This provides a single source of truth for all configuration dropdown values
/// shared between the frontend web dashboard and the tray application.
/// Values are generated at build-time by build.ps1 from frontend/src/config/ui-options.json
/// </summary>
public class UIOptions
{
    private static readonly Lazy<UIOptions> _instance = new(() => new UIOptions());
    public static UIOptions Instance => _instance.Value;

    private UIOptions() { }

    // ========== DROPDOWN VALUES ==========

    /// <summary>
    /// Get update interval options (Agent Rate) in seconds with display labels
    /// </summary>
    public (double Value, string Label)[] GetUpdateIntervals() => UIOptionsAutoGenerated.UpdateIntervals;

    /// <summary>
    /// Get fan step options (percentage)
    /// </summary>
    public (int Value, string Label)[] GetFanSteps() => UIOptionsAutoGenerated.FanSteps;

    /// <summary>
    /// Get hysteresis options in °C
    /// </summary>
    public (double Value, string Label)[] GetHysteresisOptions() => UIOptionsAutoGenerated.HysteresisOptions;

    /// <summary>
    /// Get emergency temperature options in °C with display labels
    /// </summary>
    public (int Value, string Label)[] GetEmergencyTemps() => UIOptionsAutoGenerated.EmergencyTemps;

    /// <summary>
    /// Get log level options
    /// </summary>
    public (string Value, string Label)[] GetLogLevels() => UIOptionsAutoGenerated.LogLevels;

    /// <summary>
    /// Get failsafe speed options (percentage) - fan speed when backend disconnected
    /// </summary>
    public (int Value, string Label)[] GetFailsafeSpeedOptions() => UIOptionsAutoGenerated.FailsafeSpeedOptions;

    // ========== LABELS ==========

    /// <summary>
    /// Get label for a configuration option
    /// </summary>
    public string GetLabel(string key) => key switch
    {
        "fanControl" => UIOptionsAutoGenerated.FanControlLabel,
        "logLevel" => UIOptionsAutoGenerated.LogLevelLabel,
        "emergencyTemp" => UIOptionsAutoGenerated.EmergencyTempLabel,
        "failsafeSpeed" => UIOptionsAutoGenerated.FailsafeSpeedLabel,
        "updateInterval" => UIOptionsAutoGenerated.UpdateIntervalLabel,
        "fanStep" => UIOptionsAutoGenerated.FanStepLabel,
        "hysteresis" => UIOptionsAutoGenerated.HysteresisLabel,
        _ => key
    };

    // ========== TOOLTIPS ==========

    /// <summary>
    /// Get raw tooltip template for a configuration option (contains placeholders like {agentInterval})
    /// </summary>
    public string GetTooltip(string key) => key switch
    {
        "fanControl" => UIOptionsAutoGenerated.FanControlTooltip,
        "logLevel" => UIOptionsAutoGenerated.LogLevelTooltip,
        "emergencyTemp" => UIOptionsAutoGenerated.EmergencyTempTooltip,
        "failsafeSpeed" => UIOptionsAutoGenerated.FailsafeSpeedTooltip,
        "updateInterval" => UIOptionsAutoGenerated.UpdateIntervalTooltip,
        "fanStep" => UIOptionsAutoGenerated.FanStepTooltip,
        "hysteresis" => UIOptionsAutoGenerated.HysteresisTooltip,
        _ => ""
    };

    /// <summary>
    /// Get tooltip with placeholders replaced by actual values
    /// </summary>
    public string GetInterpolatedTooltip(string key, Dictionary<string, object> values)
    {
        var template = GetTooltip(key);
        return UIOptionsAutoGenerated.InterpolateTooltip(template, values);
    }
}
